# Generated by Django 3.0.6 on 2020-05-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price_in_usd', models.CharField(max_length=255)),
                ('price_in_uah', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('range', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
