# Generated by Django 3.0.6 on 2020-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200509_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='link',
            field=models.URLField(unique=True, verbose_name='Link for Car'),
        ),
    ]
