# Generated by Django 3.0.6 on 2020-05-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200509_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='link',
            field=models.URLField(verbose_name='Link for Car'),
        ),
    ]
